# Generated by Django 2.0.4 on 2018-05-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morphology',
            fields=[
                ('morpho_id', models.IntegerField(db_column='morpho_id', primary_key=True, serialize=False)),
                ('lv1', models.CharField(blank=True, db_column='lv1', max_length=45, null=True)),
                ('lv2', models.CharField(blank=True, db_column='lv2', max_length=45, null=True)),
                ('lv3', models.CharField(blank=True, db_column='lv3', max_length=45, null=True)),
                ('verb', models.CharField(blank=True, db_column='verb', max_length=45, null=True)),
            ],
            options={
                'db_table': 'morphology',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantHasMorphology',
            fields=[
                ('plant', models.ForeignKey(db_column='Plant_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='plant.Plant')),
            ],
            options={
                'db_table': 'plant_has_morpho',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={},
        ),
    ]
