# Generated by Django 2.0.4 on 2018-04-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={},
        ),
    ]
