# Generated by Django 2.0.4 on 2018-05-19 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20180421_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='log_box_plot',
            field=models.FloatField(blank=True, default='NA'),
            preserve_default=False,
        ),
    ]
