# Generated by Django 2.0.4 on 2018-05-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_auto_20180519_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='familia',
            field=models.ForeignKey(blank=True, db_column='Familia_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plant.Familia'),
        ),
        migrations.AddField(
            model_name='plant',
            name='genus',
            field=models.ForeignKey(blank=True, db_column='Genus_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plant.Genus'),
        ),
    ]
